name: augr

channels:
  - conda-forge
dependencies:
  - python>=3.8
  - numpy
  - ros-rosbag
  - ros-rospy
  - pyrosbag
  - wheel
  # - pyrealsense2
  - opencv-python
  - scipy
  - sklearn
  - opencv-python-headless
  # - pip:
  #   - 