name: augr

dependencies:
  - pip
  - python>=3.8
  - numpy
  - wheel
  # - pyrealsense2
  - pip:
    - imutils
    - scipy
    - sklearn
    - opencv-python
    - opencv-python-headless
    - autocrop
    - ngt
    - torch
    - torchvision
    - facenet-pytorch
    - pandas